### ISSUE TITLE
Missing 'Accept' Header Property in API Documentation: application/json,application/xml

### ISSUE THREAD

**Issue by ghost** [LukeHagar/plex-docs#2]
I noticed that the API documentation is missing information regarding the 'Accept' header property to be included in API requests. As a result, the default response format for API requests is XML, which can be quite inconvenient for data processing. 

I suggest adding the 'Accept' header property with 'application/json,application/xml' values to allow users to specify the desired response format. This will enable us to receive the API response in JSON format, which is more compatible with various data processing tools and technologies.

![image](https://github.com/LukeHagar/plex-docs/assets/78251524/359d0617-23f9-48a9-a2f4-6bd42a03c943)

**Comment by LukasParke** [comment]
Hi @kvdo2 👋,

Here is a little info about it for the OpenAPI Specification. 
https://stackoverflow.com/a/62593737 

I think the response content sections that support XML just need an application/xml section added

**Comment by ghost** [comment]
Sorry, I found an error in my previous test results. If Plex's API request is not set to Accept, XML is returned by default. XML is a nightmare for me.

**Comment by LukasParke** [comment]
Might I ask what your building? 

I have been working a little bit on Plex SDKs as well

**Comment by ghost** [comment]
A Raycast Extension ( base on React and Typescript) . https://github.com/kvdo2/Audiences#plex-movie-history
It's just used to check my library and the viewing progress of the movie. Now I'm trying to reproduce the function of matching metadata.

**Comment by LukasParke** [comment]
You are welcome to take a stab at using this: https://www.npmjs.com/package/@lukehagar/plexjs

**Comment by ghost** [comment]
I will try plexjs, thank you!
